name: Pull Request
on: [ pull_request ]
jobs:
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit Tests
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: 8
          cache: gradle
      - name: Test
        run: |
          ./gradlew clean test  

